services:
  back:
    build: ./php
    ports:
      - 8000:80
      # Este puerto tiene que ser compatible con el del dockerfile (el 80)
    volumes:
      - scripts:/var/www/html
    depends_on:
      - db
  db:
    build: ./bbdd
    container_name: base_datos
    ports:
      - 4000:3306
      # El puerto 3306 puede cambiar
    volumes:
      - datos_bd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=bd
    ports:
      - 9000:80
    depends_on:
      - db
volumes:
 scripts:
 datos_bd: