services:
  laravel:
    container_name: laravel
    build: ./docker-laravel
    restart: always
    ports:
      - 80:80
    volumes:
      - scripts:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_DATABASE=laravel
    volumes:
      - datos_bbdd:/var/lib/mysql 
volumes:
  scripts:
  datos_bbdd: