services:
  backend:
    container_name: laravel
    build: ./laravel_pintores
    restart: always
    ports:
      - 8000:80
    volumes:
      - scripts:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_DATABASE=laravel
    volumes:
      - datos_bbdd:/var/lib/mysql 
volumes:
  scripts:
  datos_bbdd: